swagger: '2.0'
info:
  version: '1.0.0'
  title: EpicLand API
  description: A fitness API that provides workout routines and related nutrition information.
  contact:
    name: MPM FITNIT
host: localhost:10010
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /exercises:
    get:
      description: returns all exercises
      # used as the method name of the controller
      operationId: getAllExercises
      responses:
        "200":
          description: get array of all exercises
          schema:
            type: array
            items:
              $ref: '#/definitions/exercise'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /exercises/{id}:
    get:
      description: Returns a specific exercise based on a single ID. 
      operationId: findExerciseById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of exercise to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: exercise response
          schema:
            $ref: '#/definitions/exercise'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /users:
    post:
      description: Creates a new user in the database 
      operationId: addNewUser
      produces:
        - application/json
      parameters:
        - name: newUser
          in: body
          description: new user to add to the database
          required: true
          schema:
            $ref: '#/definitions/newUser'
      responses:
        '200':
          description: New user response
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /users/{id}:
    get:
      description: Returns a user information based on a single ID. The user must be authorized to access.  
      operationId: getUserById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the user to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: user-specific response
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    patch:
      description: updates specified properties of the specific user.
      operationId: patchUserProfile
      produces:
        - application/json
      parameters:
        - name: user profile
          in: body
          description: Insert specifiec data to update User in the database
          required: false
          type: string
          schema:
            $ref: '#/definitions/updateUser'
      responses:
        '200':
          description: user-specific response
          schema:
            $ref: '#/definitions/updateUser'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  exercise:
    type: object
    required:
        - id
        - name
        - description
        - equipment_type
        - bg_id
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
      equipment_type:
        type: string
      bg_id:
        type: integer
        format: int64
  newUser:
    type: object
    required:
      - first_name
      - last_name
      - email
      - password
      - weight
    properties:
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      password:
        type: string
      weight:
        type: integer
        format: int32
  user:
    type: object
    required:
      - id
      - first_name
      - last_name
      - email
      - password
      - weight
    properties:
      id: 
        type: integer
        format: int32
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      password:
        type: string
      weight:
        type: integer
        format: int32
  updateUser:
    type: object
    properties:
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      password:
        type: string
      weight:
        type: integer
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  
